### ISSUE TITLE
Unresolved reference: functionWithoutArgs

### ISSUE THREAD

**Issue by mirapham** [Morfly/ksp-sample#1] opened 2021-10-07 09:47 UTC
Hi,
I tried to run main() function in Main.kt class but there is error "Unresolved reference: functionWithoutArgs". So I can not run.
Pls help with this.

<img width="464" alt="Screenshot 2021-10-07 at 5 46 41 PM" src="https://user-images.githubusercontent.com/33545109/136361125-3f4d7e85-0267-4947-81b5-caa9b78e6616.png">

Thanks

**Comment by Morfly** [comment] 2021-10-07 15:05
Hi,
Please let me know if you're building the `completed` project or do you use a `start` directory by following the blog post?

I've seen this issue once or twice on one of the beta versions of KSP. To me, it looked like a bug with KSP but the tips below helped me to fix it.

- Could you please try to run a `./gradlew clean` in `completed` or `start` project directories (depending on which one you are using) and run the `main` function again?

- If it does not help, I would suggest also removing all the content of the `main` function and run it with the empty body. After the successful build please restore its content (`functionWithoutArgs` and `myAmazingFunction` calls) and see if your IDE can recognize them. Also, please check the contents of a `main-project/build/generated/ksp/main/kotlin` directory. It should contain the generated file. 

- If none of the above works for you, please open the `main-project/build.gradle.kts` file and add the following lines to it:
```kotlin
plugins {
    ...<all other plugins>
    application
}

application {
    mainClass.set("com.morfly.MainKt")
}
...<all other content>
``` 
The `application` plugin will allow you to run the project from the command line. Try to run `./gradlew main-project:run` command and check if it works.

Please, let me know if it helps.

**Comment by bfreuden** [comment] 2022-05-11 18:28
Hi,
Thank you for sharing this example!
I'm having the same issue: screenshot is exactly the same as the OP's (on the `completed` project).
Please note that everything is working properly when running gradle from the command line:

```
bruno@hearne:~/dev/github/ksp-sample/completed$ gradle main-project:run
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':annotations', ':main-project'

> Task :main-project:run
Hello from functionWithoutArgs
Hello from myAmazingFunction
```
Once gradle has been run from the command-line, IntelliJ is happy.
But run...
```
gradle clean
```
... and the issue is back.

It seems somehow that IntelliJ is unable to invoke ksp code generation, although it is configured to use gradle:
![image](https://user-images.githubusercontent.com/5137152/167919246-da46843a-e3f0-451b-8aed-459db9aa5abd.png)

![image](https://user-images.githubusercontent.com/5137152/167919966-ab1d2d6b-4ba5-4a35-b43b-bd6cc9dece62.png)

Do you know if it is expected to be working?
Thank you!

**Comment by Morfly** [comment] 2024-09-10 22:06
This should be resolved with the latest versions of KSP.

**Closed as completed by Morfly** 2024-09-10 22:06 UTC
